# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: R0yal
email: R0yal@openmailbox.org
description: > # this means to ignore newlines until "baseurl:"
  A blog about linux, security and little bit in-between.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://R0yal.github.io" # the base hostname & protocol for your site
github_username:  R0yal

# Build settings
markdown: kramdown
